# Generated by Django 4.1 on 2022-08-17 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 9, 8, 0, 819176, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
