# Generated by Django 4.1 on 2022-08-17 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_urlshortener_expire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlshortener',
            name='active',
        ),
    ]
